app = "binance-signal-bot"
primary_region = "fra"

[build]
  builder = "paketobuildpacks/builder:base"

[[http_service.ports]]
  handlers = ["http"]
  port = 80
  force_https = true
  auto_stop_machines = false
