app = "binance-signal-bot-s37rbq-nameless-sea-1323"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
    restart_limit = 6
