app = "binance-signal-bot-s37rbq-nameless-sea-1323"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = [8080]
  auto_rollback = true

[deploy]
  release_command = ""

[build]
  image = "registry.fly.io/binance-signal-bot:latest"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    restart_limit = 0
