app = "binance-signal-bot-s37rbq-nameless-sea-1323"

kill_signal = "SIGINT"
kill_timeout = 10

[env]
  PORT = "8080"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  
  [[http_service.ports]]
    handlers = ["http"]
    port = 80
    
  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[http_service.tcp_checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    restart_limit = 5
