app = "binance-signal-bot-s37rbq-nameless-sea-1323"

[env]
  TELEGRAM_TOKEN = "7697993850:AAFXT0gI310499hrGUWwE3YUZr40jlHLzzo"
  FLY_APP_NAME = "binance-signal-bot-s37rbq-nameless-sea-1323"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[deploy]
  region = "fra"
